name: Release lib-ml

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps & NLTK data
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] build
          python - <<'PY'
          import nltk, ssl
          try:
              ssl._create_default_https_context = ssl._create_unverified_context
          except AttributeError:
              pass
          nltk.download("stopwords", quiet=True)
          PY

      - name: Build distribution files
        run: python -m build

      - uses: actions/upload-artifact@v4
        with:
          name: lib-ml-dist
          path: dist/*